In [2]:
import gmaps
import pandas as pd

# Google developer API key
from config import gkey

# Configure gmaps
gmaps.configure(api_key=gkey)

In [3]:
# Create aiport dataframe
airport_df = pd.read_csv('../Resources/Airport_Output.csv')
airport_df.dropna()
airport_df.head()

,Unnamed: 0,City,State,Lat,Lng,Airport Name,Airport Address,Airport Rating
0,0,New York City,New York,40.712775,-74.005973,Newark Liberty International Airport,"3 Brewster Rd, Newark",3.2
1,1,Los Angeles,California,34.052234,-118.243685,Los Angeles International Airport,"1 World Way, Los Angeles",3.5
2,2,Chicago,Illinois,41.878114,-87.629798,O'Hare International Airport,"10000 W O'Hare Ave, Chicago",3.6
3,3,Houston,Texas,29.760427,-95.369803,William P. Hobby Airport,"7800 Airport Blvd, Houston",4.0
4,4,Philadelphia,Pennsylvania,39.952584,-75.165222,Philadelphia International Airport,"8000 Essington Ave, Philadelphia",3.3

In [4]:
# Store latitude and longitude in locations
locations = airport_df[["Lat", "Lng"]]

# Fill NaN values and convert to float
rating = airport_df["Airport Rating"].astype(float)

          Lat         Lng
0   40.712775  -74.005973
1   34.052234 -118.243685
2   41.878114  -87.629798
3   29.760427  -95.369803
4   39.952584  -75.165222
5   33.448377 -112.074037
6   29.424122  -98.493628
7   32.715738 -117.161084
8   32.776664  -96.796988
9   37.338208 -121.886329
10  30.267153  -97.743061
11  30.332184  -81.655651
12  37.774929 -122.419415
13  39.768403  -86.158068
14  39.961176  -82.998794
15  32.755488  -97.330766
16  35.227087  -80.843127
17  47.606209 -122.332071
18  39.739236 -104.990251
19  31.761878 -106.485022
20  42.331427  -83.045754
21  38.907192  -77.036871
22  42.360083  -71.058880
23  35.149534  -90.048980
24  36.162664  -86.781602
25  45.523062 -122.676481
26  35.467560  -97.516428
27  36.169941 -115.139830
28  39.290385  -76.612189
29  38.252665  -85.758456
..        ...         ...
70  41.652805  -83.537867
71  40.813616  -96.702596
72  28.538335  -81.379237
73  32.640054 -117.084196
74  40.728157  -74.077642
75  33.306160 -111.841250
76  41.079273  -85.139351
77  42.886447  -78.878369
78  35.994033  -78.898619
79  27.767601  -82.640291
80  33.684567 -117.826505
81  27.530567  -99.480324
82  33.577863 -101.855167
83  43.073052  -89.401230
84  33.352826 -111.789027
85  36.850769  -76.285873
86  39.529633 -119.813803
87  36.099860  -80.244216
88  33.538652 -112.185987
89  25.857596  -80.278106
90  32.912624  -96.638883
91  33.494170 -111.926052
92  32.814018  -96.948894
93  36.768209  -76.287493
94  36.198859 -115.117501
95  37.548270 -121.988572
96  30.451468  -91.187147
97  37.540725  -77.436048
98  43.618710 -116.214607
99  34.108345 -117.289765

[100 rows x 2 columns]

In [ ]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

![08-Airport_Heatmap.png](../Images/08-Airport_Heatmap.png)

In [ ]:
# BONUS
# Plost as a Hybrid map
fig = gmaps.figure(map_type="HYBRID")

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)

fig.add_layer(heat_layer)
fig

![08-Hybrid_Map.png](../Images/08-Hybrid_Map.png)

In [ ]:
# BONUS
# Plot as a Terrain map
fig = gmaps.figure(map_type="TERRAIN")

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)

fig.add_layer(heat_layer)
fig

![08-Terrain_Map.png](../Images/08-Terrain_Map.png)